cert-manager:
  # Gateway API support für TLS-Zertifikate an Gateway-Ressourcen
  config:
    enableGatewayAPI: true

  # When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted.
  enableCertificateOwnerRef: false

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 32Mi

  # Enables default network policies for cert-manager.
  networkPolicy:
    # Create network policies for cert-manager.
    enabled: false

  # Optional default issuer to use for ingress resources.
  # +docs:property=ingressShim.defaultIssuerName
  # defaultIssuerName: ""

  # Optional default issuer kind to use for ingress resources.
  # defaultIssuerKind: ""

  # Optional default issuer group to use for ingress resources.
  # defaultIssuerGroup: ""

  prometheus:
    # Enable Prometheus monitoring for the cert-manager controller and webhook.
    enabled: true

    servicemonitor:
      # Create a ServiceMonitor to add cert-manager to Prometheus.
      enabled: false
    # Note that you cannot enable both PodMonitor and ServiceMonitor as they are mutually exclusive. Enabling both will result in an error.
    podmonitor:
      # Create a PodMonitor to add cert-manager to Prometheus.
      enabled: false
  webhook:
    # If `replicas > 1`, consider setting `webhook.podDisruptionBudget.enabled=true`.
    replicaCount: 1

    podDisruptionBudget:
      enabled: false
      minAvailable: 1
      maxUnavailable: 1

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 32Mi

    # Enables default network policies for webhooks.
    networkPolicy:
      enabled: false

  cainjector:
    enabled: true
    replicaCount: 1

    # Enables default network policies for cainjector.
    networkPolicy:
      enabled: false

    podDisruptionBudget:
      enabled: false
      minAvailable: 1
      maxUnavailable: 1

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 32Mi

  startupapicheck:
    # Enables the startup api check.
    enabled: true

    jobAnnotations:
      helm.sh/hook: post-install
      helm.sh/hook-weight: "1"
      helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded

    resources:
      requests:
        cpu: 10m
        memory: 32Mi

