type: valuesOnly
project: platform-core

# External Helm chart used for this values-only app.
chart:
  name: metrics-server
  repoURL: https://kubernetes-sigs.github.io/metrics-server/
  version: "3.13.0"

# Helm release destination namespace.
destinationNamespace: kube-system

# Which values file to apply from this directory.
valuesFile: values.yaml

argocd:
  ignoreDifferences:
    - group: apiregistration.k8s.io
      kind: APIService
      name: v1beta1.metrics.k8s.io
      jsonPointers:
        - /spec/caBundle
        - /spec/insecureSkipTLSVerify
