apiVersion: v2
name: kyverno-wrapper
description: Wrapper Chart for Kyverno - Kubernetes Native Policy Management
type: application
dependencies:
  - name: kyverno
    repository: https://kyverno.github.io/kyverno/
    version: "3.6.2"
version: 1.0.0
appVersion: v1.16.2
