---
type: valuesOnly
project: platform-core

chart:
  name: grafana
  repoURL: https://grafana-community.github.io/helm-charts
  version: "11.3.6"

destinationNamespace: monitoring

valuesFile: values.yaml

argocd:
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.rules[].backendRefs[].group
        - .spec.rules[].backendRefs[].kind
