---
apiVersion: v2
name: cilium
description: Wrapper Chart for Cilium CNI
type: application
dependencies:
  - name: cilium
    repository: https://helm.cilium.io/
    version: 1.18.4
version: 0.0.0
appVersion: 1.18.4

